#####
## submission via API for rat files (taxon id: 10116)
#
TAXON=10116
SPECIES=RGD
APITOKEN=`cat api.token`

ALLELE_SPEC="${AGR_RELEASE}_ALLELE_${SPECIES}"
ALLELE_LOC="data/$BATCH/${MOD_NAME}_${AGR_VER}_allele.${TAXON}.json"
ALLELE_FILE="${ALLELE_SPEC}=@${ALLELE_LOC}"
echo "$ALLELE_FILE"

VARIANT_SPEC="${AGR_RELEASE}_VARIATION_${SPECIES}"
VARIANT_LOC="data/$BATCH/${MOD_NAME}_${AGR_VER}_variant.${TAXON}.json"
VARIANT_FILE="${VARIANT_SPEC}=@${VARIANT_LOC}"
echo "$VARIANT_FILE"

EXPR_SPEC="${AGR_RELEASE}_EXPRESSION_${SPECIES}"
EXPR_LOC="data/$BATCH/${MOD_NAME}_${AGR_VER}_expression.${TAXON}.json"
EXPRESSION_FILE="${EXPR_SPEC}=@${EXPR_LOC}"
echo "$EXPRESSION_FILE"

PHENOTYPE_SPEC="${AGR_RELEASE}_PHENOTYPE_${SPECIES}"
PHENOTYPE_LOC="data/$BATCH/${MOD_NAME}_${AGR_VER}_phenotype.${TAXON}.json"
PHENOTYPE_FILE="${PHENOTYPE_SPEC}=@${PHENOTYPE_LOC}"
echo "$PHENOTYPE_FILE"

DISEASE_SPEC="${AGR_RELEASE}_DAF_${SPECIES}"
DISEASE_LOC="data/$BATCH/${MOD_NAME}_${AGR_VER}_disease.${TAXON}.json"
DISEASE_FILE="${DISEASE_SPEC}=@${DISEASE_LOC}"
echo "$DISEASE_FILE"

GENE_SPEC="${AGR_RELEASE}_BGI_${SPECIES}"
GENE_LOC="data/$BATCH/${MOD_NAME}_${AGR_VER}_gene.${TAXON}.json"
GENE_FILE="${GENE_SPEC}=@${GENE_LOC}"
echo "$GENE_FILE"

AGM_SPEC="${AGR_RELEASE}_AGM_${SPECIES}"
AGM_LOC="data/$BATCH/${MOD_NAME}_${AGR_VER}_affectedGenomicModel.${TAXON}.json"
AGM_FILE="${AGM_SPEC}=@${AGM_LOC}"
echo "$AGM_FILE"

GFF_SPEC="${AGR_RELEASE}_GFF_${SPECIES}"
GFF_LOC="data/$BATCH/${MOD_NAME}_${AGR_VER}_GFF.${TAXON}.gff3"
GFF_FILE="${GFF_SPEC}=@${GFF_LOC}"
echo "$GFF_FILE"

curl -k \
 -H "Authorization: Bearer $APITOKEN" \
 -X POST "https://fms.alliancegenome.org/api/data/submit" \
 -F "$DISEASE_FILE" \
 | tee do_rat_submission.log

echo "=== OK ==="
